name: aur
on:
  release:
jobs:
  aur-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate PKGBUILD
        run: |
          cat > PKGBUILD <<EOF
          # Maintainer: Aryan Kothari aryan@aryankothari.dev
          pkgname=longhorn-backup-repacker
          pkgver=${GITHUB_REF#refs/tags/}
          pkgrel=1
          pkgdesc="A tool to repack Longhorn backup files"
          arch=('any')
          url="https://github.com/thearyadev/longhorn-backup-repacker"
          license=('MIT')
          depends=('go')
          makedepends=('git')

          source=("$pkgname-$pkgver.tar.gz::https://github.com/thearyadev/$pkgname/archive/v$pkgver.tar.gz")
          sha256sums=('SKIP')

          build() {
              cd "$pkgname-$pkgver"
              export CGO_CPPFLAGS="${CPPFLAGS}"
              export CGO_CFLAGS="${CFLAGS}"
              export CGO_CXXFLAGS="${CXXFLAGS}"
              export CGO_LDFLAGS="${LDFLAGS}"
              export GOFLAGS="-buildmode=pie -trimpath -ldflags=-linkmode=external -mod=readonly -modcacherw"
              go build -o $pkgname .
          }

          package() {
              cd "$pkgname-$pkgver"
              sudo install -Dm755 "$pkgname" "/usr/bin/$pkgname"
              sudo install -Dm644 LICENSE "/usr/share/licenses/$pkgname/LICENSE"
          }


      - name: Publish AUR package
        uses: KSXGitHub/github-actions-deploy-aur@v4.1.1
        with:
          pkgname: longhorn-backup-repacker
          pkgbuild: ./PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update AUR package
          ssh_keyscan_types: rsa,ecdsa,ed25519
